trigger:
  - main
pool:
  name: Azure Pipelines
parameters:
  - name: Environment
    type: string
    default: Sandbox
    values:
      - NonProduction

resources:
  repositories:
  - repository: self
  - repository: IaC Code testing
    type: git
    name: IaC Code testing
    ref: master

variables:
  - template: variables.yaml

stages:
  
  - stage: Generate_Plan_for_sharedservices
    jobs:
      - deployment: sharedservices
        environment: ${{parameters.Environment}}
        displayName: Generate Plan for sharedservices
        variables:
          - group: external-tenant-sharedservices-variable
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: IaC Code testing
                - checkout: self  
                  displayName: Checkout repository
                - task: AzureCLI@2
                  displayName: Generate Plan for sharedservices
                  enabled: true
                  inputs:
                    workingDirectory: $(System.DefaultWorkingDirectory)/platform-sharedservices-alz-deployment/sharedservices
                    scriptLocation: inlineScript
                    addSpnToEnvironment: "true"
                    scriptType: bash
                    inlineScript: |2-
                                                    export ARM_CLIENT_ID=$(ARM_CLIENT_ID)
                                                    export ARM_CLIENT_SECRET=$(ARM_CLIENT_SECRET)
                                                    export ARM_SUBSCRIPTION_ID=$(ARM_SUBSCRIPTION_ID)
                                                    export ARM_TENANT_ID=$(ARM_TENANT_ID)
                                                    

                                                   # Terraform Init
                                                    terraform init -backend-config="resource_group_name=${{ variables.terraformStorageRG }}" -reconfigure \
                                                        -backend-config="storage_account_name=${{ variables.terraformStorageAccount }}" \
                                                        -backend-config="container_name=${{ variables.terraformStorageContainer}}" \
                                                        -backend-config="key=sharedservices-terraform.tfstate"\
                                                        -backend-config="use_azuread_auth=true"


                                                    # Terraform PlanTerraform Init
                                                    terraform plan -var-file sharedservices.tfvars -out="main.tfplan" -input=false
                    azureSubscription: ${{ variables.serviceConnection}}
                - task: PublishBuildArtifacts@1
                  displayName: Publish Build Artifacts
                  enabled: true
                  inputs:
                    ArtifactName: sharedservices
                    PathtoPublish: $(System.DefaultWorkingDirectory)/platform-sharedservices-alz-deployment/sharedservices/main.tfplan
                    publishLocation: Container

  - stage: Apply_Plan_for_sharedservices
    jobs:
      - deployment: sharedservices
        environment: ${{ parameters.Environment }}
        displayName: Apply Plan for sharedservices
        variables:
          - group: external-tenant-sharedservices-variable
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: IaC Code testing
                - checkout: self
                
                  displayName: Checkout repository
                
                - task: AzureCLI@2
                  displayName: Apply Plan for sharedservices
                  enabled: true
                  inputs:
                    workingDirectory: $(System.DefaultWorkingDirectory)/platform-sharedservices-alz-deployment/sharedservices
                    scriptLocation: inlineScript
                    addSpnToEnvironment: "true"
                    scriptType: bash
                    inlineScript: |2-
                                                    
                                                    cp $(Pipeline.Workspace)/sharedservices/main.tfplan $(System.DefaultWorkingDirectory)/platform-sharedservices-alz-deployment/sharedservices

                                                    export ARM_CLIENT_ID=$(ARM_CLIENT_ID)
                                                    export ARM_CLIENT_SECRET=$(ARM_CLIENT_SECRET)
                                                    export ARM_SUBSCRIPTION_ID=$(ARM_SUBSCRIPTION_ID)
                                                    export ARM_TENANT_ID=$(ARM_TENANT_ID)
                                                    

                                                    # Terraform Init
                                                    terraform init -backend-config="resource_group_name=${{ variables.terraformStorageRG }}" -reconfigure \
                                                        -backend-config="storage_account_name=${{ variables.terraformStorageAccount }}" \
                                                        -backend-config="container_name=${{ variables.terraformStorageContainer}}" \
                                                        -backend-config="key=sharedservices-terraform.tfstate"\
                                                        -backend-config="use_azuread_auth=true"

                                                    # Terraform Apply
                                                    terraform apply main.tfplan
                    azureSubscription: ${{ variables.serviceConnection}}
    dependsOn: Generate_Plan_for_sharedservices

